### ISSUE TITLE
Replace @ConsumerType annotation from Bnd with OSGi?

### ISSUE THREAD

**Issue by yan-kisen** [adobe/aem-component-generator#10]
Very interesting project.

I'm curious whether `aQute.bnd.annotation.ConsumerType` annotation should be replaced with `org.osgi.annotation.versioning.ConsumerType`.

This seems to be the case for the wcm-core-components?

**Comment by HitmanInWis** [comment]
Indeed.  Feel free to put up a PR resolving the issue, else maybe someone from Bounteous will get to it in the next few weeks.

**Comment by HitmanInWis** [comment]
@brandonmaynard want to knock this one out?

**Comment by HitmanInWis** [comment]
This is resolved.
