### ISSUE TITLE
Create Configuration for Code Owner

### ISSUE THREAD

**Issue by brandonmaynard** [adobe/aem-component-generator#11]
In all of our template text files, we have `<CODEOWNER>` and a manual step in the README.md to replace this value. We should make this a project setting configuration and programmatically replace this value with the configured value.

Once #9 is merged, I will create a PR for this change (I have the changes already coded but I was using #9's branch to avoid conflicts)

**Comment by HitmanInWis** [comment]
Completely agreed with this idea.

**Comment by HitmanInWis** [comment]
This is resolved by #13
