### ISSUE TITLE
Maintained by Bounteous?

### ISSUE THREAD

**Issue by HitmanInWis** [adobe/aem-component-generator#2]
Would it make sense to have at least one Bounteous dev added as a maintainer for this project, being the original contributors?

**Comment by vladbailescu** [comment]
Hi @HitmanInWis , I merged the PR for the initial commit, thank you very much for this contribution. I added you as an admin of the repository so you can add as many collaborators from Bounteous.

**Comment by HitmanInWis** [comment]
Thank you @vladbailescu !
