### ISSUE TITLE
[Feature Request]: Create Unit Tests Skeleton

### ISSUE THREAD

**Issue by prahladmishra** [adobe/aem-component-generator#32]
First of all awesome generator, it will bring constency and save a lot of time. 

Similar to creating HTL, Dialogs and Java classes, can we also generate unit test files as well.

**Comment by HitmanInWis** [comment]
That would indeed be awesome.  The tests for components inside the WCM Core project for components do follow a pretty similar pattern, so I think it's within the realm of possibility, but also likely quite involved.  If anyone wants to tackle this giant, even with a simple incremental start to it, I'd welcome a PR!

**Comment by sujeet-singh** [comment]
Hi HitmanInWis,

I have raised a PR on this. Could you please take a look?

**Comment by HitmanInWis** [comment]
yes, absolutely plan to do so...just been very busy of late.  I was excited to see it come through, and definitely will try to get to it this week.

**Comment by HitmanInWis** [comment]
This is resolved by https://github.com/adobe/aem-component-generator/pull/34

**Comment by prahladmishra** [comment]
@sujeet-singh : Thank you for looking into this. It will definitely make developers think about writing test cases for the components.
