### ISSUE TITLE
Jackson dependency version too wide

### ISSUE THREAD

**Issue by karollewandowski** [adobe/aem-component-generator#39]
Hi, there is a problem with `jackson-databind` dependency. Currently, it is defined as:
```
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>[2.9.9.1,)</version>
</dependency>
```
Today I tried to build the project and was getting an error that `ObjectMapper` class doesn't have `configure()` method.
This is because in `jackson-databind` 3.0 they moved configure methods to `MapperBuilder`.
Dependency should be less than 3.0.

**Comment by HitmanInWis** [comment]
Thanks for the quick fix!
