### ISSUE TITLE
Add generated clientlib files

### ISSUE THREAD

**Issue by brandonmaynard** [adobe/aem-component-generator#8]
Would it make sense to generate the clientlib definition in `clientlibs/site`? At the very least, we can stub the `categories` and `dependencies` like how we stub the `isConfigured` on the HTL. 

Also, I think it would make sense to autogenerate the 'js.txt' and 'css.txt' files and include the paths/filenames for the autogenerated JS/CSS files as well. Thoughts?

**Comment by HitmanInWis** [comment]
Yes, we should definitely create the `site` folder as a bonified Client Library (didnt realize it wasnt) and we should add `allowProxy={Boolean}true` as well.  Not sure what `dependencies` you're thinking of, but certainly we can generate the `categories` based on the component name.

We should also add the js.txt and css.txt files.

**Comment by HitmanInWis** [comment]
This issue was resolved by PR #9
